### ISSUE TITLE
some penalty / DQ logic rework

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#241]
penalties is all based on r3e impl, so if you have a DT or SG pen, the app loses it's shit if you don't complete it in 3 laps - is this correct? It assumes r3e's approach is correct

**Comment by TheIronWolfModding** [comment]
It is kind of correct for ISI games too.  However, this area is a mess really.  For example in rF2, nothing really happens if you don't complete penalty in 3 laps.

I have asked for more details exposed by game especially wrt penalties, this is number one on priority list I asked of S397.

While it is weird that CC goes silent after 3 laps while one can still drive, I am not sure what is better alternative (without games actually fixing their bugs).

**Comment by mrbelowski** [comment]
seems that RF2's implementation is close enough to R3E's here. No idea what pCars2's implementation is, not sure that I really care at this point
