### ISSUE TITLE
rF2: User never praised for passing an opponent

### ISSUE THREAD

**Issue by TheIronWolfModding** [mrbelowski/CrewChiefV4#84]
Additionally, rF2 has LastImpactTime available, we can use this to congratulate only on clean passes.

**Comment by mrbelowski** [comment]
this might be a regression in the car class stuff - the app only reports passes when you're in the same car class as the opponent, but the class comparison was using CarClass object equality, not CarClass.carClassIdentifier equality. I've changed this but not been able to test

**Comment by TheIronWolfModding** [comment]
Thanks Jim, we may need to make CarClass Comparable, I'll look into it.

**Comment by mrbelowski** [comment]
we're doing '==' comparison on the result of CarClassEnum.ToString(). This is still a bit risky because I'm not sure how enum.ToString() behaves with respect to String internment and object equality and really can't be arsed scrabbling through the arse-end of MickySoft's shitty C# documentation to work it out.

There's another issue here which needs to be considered. Some classes are 'almost equal' - e.g. R3E DTM2013, DTM2014, DTM2015, DTM2016. We may want to consider these as the same class for the purposes of lap time comparisons etc because they use the same physics and have similar performance characteristics.

We might be able to fix both these issues by having our own static IsSameClass(carClass1, carClass2) method on CarClass. This could do the necessary null checks and the String.Equals(carClass1.getCarClassIdentifier(), carClass2.getCarClassIdentifier()). It could also have special cases for these 'almost equal' car classes

**Comment by TheIronWolfModding** [comment]
fixed!!!
