### ISSUE TITLE
rF2 Inappropriate Message: "Vytas is pitting" followed by "Vytas is in front".

### ISSUE THREAD

**Issue by TheIronWolfModding** [mrbelowski/CrewChiefV4#85]

**Comment by mrbelowski** [comment]
the "the next car is [driver name]" message is triggered when the car in front changes. This suggests that something in the RF2 data isn't behaving quite as expected - perhaps on pit entry the opponent briefly goes behind the player, then immediately afterwards he goes in front (perhaps this is just due to the layout of the pit entry vs the layout of the track).

I can disable the "the next car is..." message if the next car is in the pit, but this depends on accurate and timely pit data from the game. I'll make the change but I'm guessing to be honest

**Comment by mrbelowski** [comment]
hmm.. turns out i already check for 'isEnteringPit' - I've also added an isInPit check but I doubt this will make a difference. I don't understand why it'd do this - is it regular? Do you have duplicate opponent names?

**Comment by TheIronWolfModding** [comment]
Fixed by e81ae289b8f6ba2b5e69
